name: Swift abstractions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['abstractions/**', '.github/workflows/**']
  pull_request:
    paths: ['abstractions/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./abstractions
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.7'
      - name: Build SDK project
        run: swift build
        working-directory: ${{ env.relativePath }}
      - name: Run unit tests
        run: swift test
        working-directory: ${{ env.relativePath }}
